#!/usr/bin/env node

/**
 * Build script for Chess Assistant extension
 * Supports Chrome, Firefox, debug builds, and production builds
 */

const fs = require('fs-extra');
const path = require('path');
const archiver = require('archiver');

// Parse command line arguments
const args = process.argv.slice(2);
const flags = {
    prod: args.includes('--prod') || process.env.NODE_ENV === 'production',
    debug: args.includes('--debug'),
    firefox: args.includes('--firefox'),
    chrome: args.includes('--chrome'),
    package: args.includes('--package'),
    clean: args.includes('--clean'),
    watch: args.includes('--watch')
};

const buildType = flags.debug ? 'debug' : (flags.prod ? 'production' : 'development');
const browserType = flags.firefox ? 'firefox' : 'chrome';

const ROOT_DIR = path.join(__dirname, '..');
const DIST_DIR = path.join(ROOT_DIR, 'dist');
const SRC_DIR = path.join(ROOT_DIR, 'src');
const PUBLIC_DIR = path.join(ROOT_DIR, 'public');

const colors = {
    reset: '\x1b[0m', bright: '\x1b[1m',
    green: '\x1b[32m', yellow: '\x1b[33m', blue: '\x1b[36m', red: '\x1b[31m'
};
const log = (m, c = colors.reset) => console.log(`${c}${m}${colors.reset}`);
const logStep = m => log(`\n${colors.bright}${colors.blue}▶ ${m}${colors.reset}`);
const logSuccess = m => log(`${colors.green}✓ ${m}${colors.reset}`);
const logWarning = m => log(`${colors.yellow}⚠ ${m}${colors.reset}`);
const logError = m => log(`${colors.red}✗ ${m}${colors.reset}`);

// ─── Content script bundler ───────────────────────────────────────────────────

async function buildContentScriptBundle() {
    const entryFile = path.join(SRC_DIR, 'content', 'index.js');
    const outputFile = path.join(DIST_DIR, 'content.js');

    if (!(await fs.pathExists(entryFile))) return false;

    const orderedFiles = [];
    const visited = new Set();

    const resolveImportPath = (baseFile, importPath) => {
        const resolved = path.resolve(path.dirname(baseFile), importPath);
        return resolved.endsWith('.js') ? resolved : `${resolved}.js`;
    };

    const collect = async (filePath) => {
        if (visited.has(filePath)) return;
        visited.add(filePath);
        const source = await fs.readFile(filePath, 'utf8');
        const importRegex = /^import\s+\{\s*([^}]+)\s*\}\s+from\s+['"]([^'"]+)['"];?\s*$/gm;
        let match;
        while ((match = importRegex.exec(source)) !== null) {
            if (match[2].startsWith('.')) {
                await collect(resolveImportPath(filePath, match[2]));
            }
        }
        orderedFiles.push(filePath);
    };

    const compileModule = (source) => {
        const importRegex = /^import\s+\{\s*([^}]+)\s*\}\s+from\s+['"]([^'"]+)['"];?\s*$/gm;
        const importLines = [];
        let transformed = source.replace(importRegex, (_, names) => {
            importLines.push(`const { ${names.split(',').map(n => n.trim()).filter(Boolean).join(', ')} } = globalThis.__chessAssistantModules;`);
            return '';
        });
        const exportedNames = [];
        transformed = transformed.replace(/^export\s+class\s+(\w+)/gm, (_, n) => { exportedNames.push(n); return `class ${n}`; });
        transformed = transformed.replace(/^export\s+const\s+(\w+)/gm, (_, n) => { exportedNames.push(n); return `const ${n}`; });
        transformed = transformed.replace(/^export\s+function\s+(\w+)/gm, (_, n) => { exportedNames.push(n); return `function ${n}`; });
        if (importLines.length) transformed = `${importLines.join('\n')}\n\n${transformed}`;
        if (exportedNames.length) transformed += `\n\nObject.assign(globalThis.__chessAssistantModules, { ${[...new Set(exportedNames)].join(', ')} });\n`;
        return `(() => {\n${transformed}\n})();\n`;
    };

    await collect(entryFile);

    const chunks = [
        '// Auto-generated by scripts/build.js',
        'globalThis.__chessAssistantModules = globalThis.__chessAssistantModules || {};',
        ''
    ];
    for (const filePath of orderedFiles) {
        const source = await fs.readFile(filePath, 'utf8');
        const relativePath = path.relative(ROOT_DIR, filePath).replace(/\\/g, '/');
        chunks.push(`// Module: ${relativePath}`);
        chunks.push(compileModule(source));
    }
    await fs.writeFile(outputFile, chunks.join('\n'), 'utf8');
    return true;
}

// ─── Build steps ──────────────────────────────────────────────────────────────

async function clean() {
    logStep('Cleaning dist...');
    await fs.remove(DIST_DIR);
    await fs.ensureDir(DIST_DIR);
    logSuccess('Dist cleaned');
}

async function copyPublicFiles() {
    logStep('Copying public files...');
    const files = ['browser-polyfill.js', 'ecoA.json', 'ecoB.json', 'ecoC.json', 'ecoD.json', 'ecoE.json'];
    for (const file of files) {
        const src = path.join(PUBLIC_DIR, file);
        if (await fs.pathExists(src)) { await fs.copy(src, path.join(DIST_DIR, file)); logSuccess(`Copied ${file}`); }
        else logWarning(`${file} not found, skipping`);
    }
    const cssFile = path.join(SRC_DIR, 'styles', 'overlay.css');
    if (await fs.pathExists(cssFile)) { await fs.copy(cssFile, path.join(DIST_DIR, 'overlay.css')); logSuccess('Copied overlay.css'); }
}

async function copyIcon() {
    logStep('Handling icon...');
    const pngIcon = path.join(PUBLIC_DIR, 'icons', 'icon.png');
    const svgIcon = path.join(PUBLIC_DIR, 'icons', 'icon.svg');
    if (await fs.pathExists(pngIcon)) { await fs.copy(pngIcon, path.join(DIST_DIR, 'icon.png')); logSuccess('Copied icon.png'); }
    else if (await fs.pathExists(svgIcon)) { logWarning('icon.png missing — convert icon.svg first'); await fs.copy(svgIcon, path.join(DIST_DIR, 'icon.svg')); }
    else logWarning('No icon found');
}

async function copyStockfishFiles() {
    logStep('Copying Stockfish files...');
    let copiedCount = 0;
    for (const file of ['stockfish.js', 'stockfish.wasm']) {
        const candidates = [path.join(PUBLIC_DIR, file), path.join(PUBLIC_DIR, 'stockfish', file)];
        let src = null;
        for (const c of candidates) { if (await fs.pathExists(c)) { src = c; break; } }
        if (src) {
            await fs.copy(src, path.join(DIST_DIR, file));
            logSuccess(`Copied ${file}  (from ${path.relative(ROOT_DIR, src)})`);
            copiedCount++;
        } else {
            logWarning(`${file} not found in public/ or public/stockfish/`);
        }
    }
    if (copiedCount === 0) logError('No Stockfish files found! Place stockfish.js + stockfish.wasm in public/stockfish/');
}

async function copyManifest() {
    logStep(`Copying manifest for ${browserType} (${buildType})...`);
    const manifestFile = flags.debug ? 'manifest.debug.json' : browserType === 'firefox' ? 'manifest.firefox.json' : 'manifest.json';
    const src = path.join(PUBLIC_DIR, manifestFile);
    if (await fs.pathExists(src)) { await fs.copy(src, path.join(DIST_DIR, 'manifest.json')); logSuccess(`Using ${manifestFile}`); }
    else { logError(`Manifest ${manifestFile} not found!`); throw new Error(`Missing manifest: ${manifestFile}`); }
}

async function bundleSource() {
    logStep('Bundling source files...');

    // Background service worker
    const backgroundSrc = path.join(SRC_DIR, 'background', 'background.js');
    if (await fs.pathExists(backgroundSrc)) { await fs.copy(backgroundSrc, path.join(DIST_DIR, 'background.js')); logSuccess('Copied background.js'); }

    // Offscreen document JS (Chrome MV3 — hosts the Stockfish Worker)
    const offscreenJS = path.join(SRC_DIR, 'background', 'offscreen.js');
    if (await fs.pathExists(offscreenJS)) {
        await fs.copy(offscreenJS, path.join(DIST_DIR, 'offscreen.js'));
        logSuccess('Copied offscreen.js');
    } else {
        logWarning('offscreen.js not found in src/background/ — Chrome analysis will not work');
    }

    // Firefox Stockfish worker wrapper (applies WASM patches, then importScripts stockfish.js)
    // Must be a real extension file (not a blob) so that relative paths resolve correctly.
    const firefoxWorkerSrc = path.join(SRC_DIR, 'background', 'stockfish-worker-ff.js');
    if (await fs.pathExists(firefoxWorkerSrc)) {
        await fs.copy(firefoxWorkerSrc, path.join(DIST_DIR, 'stockfish-worker-ff.js'));
        logSuccess('Copied stockfish-worker-ff.js');
    } else {
        logWarning('stockfish-worker-ff.js not found in src/background/ — Firefox analysis will not work');
    }

    // Offscreen HTML (Chrome MV3)
    const offscreenHTML = path.join(PUBLIC_DIR, 'offscreen.html');
    if (await fs.pathExists(offscreenHTML)) {
        await fs.copy(offscreenHTML, path.join(DIST_DIR, 'offscreen.html'));
        logSuccess('Copied offscreen.html');
    } else {
        logWarning('offscreen.html not found in public/ — Chrome analysis will not work');
    }

    // Content script bundle
    const built = await buildContentScriptBundle();
    if (!built) { logError('Missing src/content/index.js'); throw new Error('Cannot build content script'); }
    logSuccess('Built content.js');

    // Popup
    for (const [src, dest] of [
        [path.join(SRC_DIR, 'popup', 'popup.js'), 'popup.js'],
        [path.join(SRC_DIR, 'popup', 'popup.html'), 'popup.html'],
        [path.join(SRC_DIR, 'popup', 'popup.css'), 'popup.css'],
    ]) {
        if (await fs.pathExists(src)) { await fs.copy(src, path.join(DIST_DIR, dest)); logSuccess(`Copied ${dest}`); }
    }
}

async function createPackage() {
    logStep('Creating package...');
    const ext = browserType === 'firefox' ? 'xpi' : 'zip';
    const filename = `chess-assistant-${browserType}-${buildType}.${ext}`;
    const output = fs.createWriteStream(path.join(ROOT_DIR, filename));
    const archive = archiver('zip', { zlib: { level: 9 } });
    return new Promise((resolve, reject) => {
        output.on('close', () => { logSuccess(`Package: ${filename} (${(archive.pointer() / 1024 / 1024).toFixed(2)} MB)`); resolve(); });
        archive.on('error', reject);
        archive.pipe(output);
        archive.directory(DIST_DIR, false);
        archive.finalize();
    });
}

function displaySummary() {
    log('\n' + '='.repeat(50));
    log(`${colors.bright}Build Summary${colors.reset}`);
    log('='.repeat(50));
    log(`Browser:    ${colors.blue}${browserType}${colors.reset}`);
    log(`Build type: ${colors.blue}${buildType}${colors.reset}`);
    log(`Output:     ${colors.blue}${DIST_DIR}${colors.reset}`);
    log('='.repeat(50) + '\n');
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function build() {
    try {
        log('\n' + colors.bright + colors.blue + '╔════════════════════════════════════════╗');
        log('║   Chess Assistant Build Script       ║');
        log('╚════════════════════════════════════════╝' + colors.reset + '\n');

        await clean();
        await copyPublicFiles();
        await copyIcon();
        await copyStockfishFiles();
        await copyManifest();
        await bundleSource();
        if (flags.package) await createPackage();

        displaySummary();
        logSuccess('Build completed successfully!');

        if (!flags.watch) {
            log('\nNext steps:');
            log(`  1. Load from ${colors.blue}dist/${colors.reset}`);
            if (browserType === 'firefox') {
                log('  2. Open about:debugging#/runtime/this-firefox → Load Temporary Add-on → dist/manifest.json');
            } else {
                log('  2. Open chrome://extensions/ → Enable Developer mode → Load unpacked → select dist/');
            }
        }
    } catch (error) {
        logError('Build failed: ' + error.message);
        process.exit(1);
    }
}

async function watch() {
    logStep('Starting watch mode...');
    const chokidar = require('chokidar');
    await build();
    let buildTimeout;
    chokidar.watch([SRC_DIR, PUBLIC_DIR], { ignored: /(^|[\/\\])\../, persistent: true, ignoreInitial: true })
        .on('all', (event, filePath) => {
            log(`\n${colors.yellow}File ${event}: ${path.relative(ROOT_DIR, filePath)}${colors.reset}`);
            clearTimeout(buildTimeout);
            buildTimeout = setTimeout(() => build(), 1000);
        });
    log(`${colors.green}Watching for changes...${colors.reset}\n`);
}

(async () => {
    if (flags.clean && !flags.watch && !flags.package) { await clean(); return; }
    if (flags.watch) await watch();
    else await build();
})();