#!/usr/bin/env node

/**
 * Build script for Chess Assistant extension
 * Supports Chrome, Firefox, debug builds, and production builds
 */

const fs = require('fs-extra');
const path = require('path');
const archiver = require('archiver');

// Parse command line arguments
const args = process.argv.slice(2);
const flags = {
    prod: args.includes('--prod') || process.env.NODE_ENV === 'production',
    debug: args.includes('--debug'),
    firefox: args.includes('--firefox'),
    chrome: args.includes('--chrome'),
    package: args.includes('--package'),
    clean: args.includes('--clean'),
    watch: args.includes('--watch')
};

// Determine build type
const buildType = flags.debug ? 'debug' : (flags.prod ? 'production' : 'development');
const browserType = flags.firefox ? 'firefox' : 'chrome';

// Paths
const ROOT_DIR = path.join(__dirname, '..');
const DIST_DIR = path.join(ROOT_DIR, 'dist');
const SRC_DIR = path.join(ROOT_DIR, 'src');
const PUBLIC_DIR = path.join(ROOT_DIR, 'public');

// Colors for console output
const colors = {
    reset: '\x1b[0m',
    bright: '\x1b[1m',
    green: '\x1b[32m',
    yellow: '\x1b[33m',
    blue: '\x1b[36m',
    red: '\x1b[31m'
};

function log(message, color = colors.reset) {
    console.log(`${color}${message}${colors.reset}`);
}

function logStep(message) {
    log(`\n${colors.bright}${colors.blue}▶ ${message}${colors.reset}`);
}

function logSuccess(message) {
    log(`${colors.green}✓ ${message}${colors.reset}`);
}

function logWarning(message) {
    log(`${colors.yellow}⚠ ${message}${colors.reset}`);
}

function logError(message) {
    log(`${colors.red}✗ ${message}${colors.reset}`);
}

/**
 * Build a browser-ready content script bundle from refactored ES modules
 */
async function buildContentScriptBundle() {
    const entryFile = path.join(SRC_DIR, 'content', 'index.js');
    const outputFile = path.join(DIST_DIR, 'content.js');

    if (!(await fs.pathExists(entryFile))) {
        return false;
    }

    const orderedFiles = [];
    const visited = new Set();

    const resolveImportPath = (baseFile, importPath) => {
        const resolved = path.resolve(path.dirname(baseFile), importPath);
        return resolved.endsWith('.js') ? resolved : `${resolved}.js`;
    };

    const collect = async (filePath) => {
        if (visited.has(filePath)) return;
        visited.add(filePath);

        const source = await fs.readFile(filePath, 'utf8');
        const importRegex = /^import\s+\{\s*([^}]+)\s*\}\s+from\s+['"]([^'"]+)['"];?\s*$/gm;
        let match;

        while ((match = importRegex.exec(source)) !== null) {
            const importPath = match[2];
            if (importPath.startsWith('.')) {
                const importedFile = resolveImportPath(filePath, importPath);
                await collect(importedFile);
            }
        }

        orderedFiles.push(filePath);
    };

    const compileModule = (source) => {
        const importRegex = /^import\s+\{\s*([^}]+)\s*\}\s+from\s+['"]([^'"]+)['"];?\s*$/gm;
        const importLines = [];

        let transformed = source.replace(importRegex, (_, importedNames) => {
            const names = importedNames
                .split(',')
                .map(n => n.trim())
                .filter(Boolean)
                .join(', ');

            importLines.push(`const { ${names} } = globalThis.__chessAssistantModules;`);
            return '';
        });

        const exportedNames = [];
        transformed = transformed.replace(/^export\s+class\s+(\w+)/gm, (_, name) => {
            exportedNames.push(name);
            return `class ${name}`;
        });
        transformed = transformed.replace(/^export\s+const\s+(\w+)/gm, (_, name) => {
            exportedNames.push(name);
            return `const ${name}`;
        });
        transformed = transformed.replace(/^export\s+function\s+(\w+)/gm, (_, name) => {
            exportedNames.push(name);
            return `function ${name}`;
        });

        if (importLines.length > 0) {
            transformed = `${importLines.join('\n')}\n\n${transformed}`;
        }

        if (exportedNames.length > 0) {
            transformed += `\n\nObject.assign(globalThis.__chessAssistantModules, { ${[...new Set(exportedNames)].join(', ')} });\n`;
        }

        return `(() => {\n${transformed}\n})();\n`;
    };

    await collect(entryFile);

    const chunks = [
        '// Auto-generated by scripts/build.js from src/content/index.js and dependencies',
        'globalThis.__chessAssistantModules = globalThis.__chessAssistantModules || {};',
        ''
    ];

    for (const filePath of orderedFiles) {
        const source = await fs.readFile(filePath, 'utf8');
        const relativePath = path.relative(ROOT_DIR, filePath).replace(/\\/g, '/');
        chunks.push(`// Module: ${relativePath}`);
        chunks.push(compileModule(source));
    }

    await fs.writeFile(outputFile, chunks.join('\n'), 'utf8');
    return true;
}

/**
 * Clean dist directory
 */
async function clean() {
    logStep('Cleaning dist directory...');
    await fs.remove(DIST_DIR);
    await fs.ensureDir(DIST_DIR);
    logSuccess('Dist directory cleaned');
}

/**
 * Copy public files (HTML, CSS, icons, etc.)
 */
async function copyPublicFiles() {
    logStep('Copying public files...');

    const filesToCopy = [
        'browser-polyfill.js',
        'ecoA.json',
        'ecoB.json',
        'ecoC.json',
        'ecoD.json',
        'ecoE.json'
    ];

    for (const file of filesToCopy) {
        const src = path.join(PUBLIC_DIR, file);
        const dest = path.join(DIST_DIR, file);

        if (await fs.pathExists(src)) {
            await fs.copy(src, dest);
            logSuccess(`Copied ${file}`);
        } else {
            logWarning(`${file} not found, skipping`);
        }
    }

    // Copy CSS
    const cssFiles = ['overlay.css'];
    for (const file of cssFiles) {
        const srcPath = path.join(SRC_DIR, 'styles', file);
        if (await fs.pathExists(srcPath)) {
            await fs.copy(srcPath, path.join(DIST_DIR, file));
            logSuccess(`Copied ${file}`);
        }
    }
}

/**
 * Copy or generate icon
 */
async function copyIcon() {
    logStep('Handling icon...');

    // Check for PNG icon first
    const pngIcon = path.join(PUBLIC_DIR, 'icons', 'icon.png');
    const svgIcon = path.join(PUBLIC_DIR, 'icons', 'icon.svg');


    if (await fs.pathExists(pngIcon)) {
        await fs.copy(pngIcon, path.join(DIST_DIR, 'icon.png'));
        logSuccess('Copied icon.png');
    } else if (await fs.pathExists(svgIcon)) {
        // SVG exists but no PNG
        logWarning('icon.svg found but icon.png missing. Please convert SVG to PNG.');
        logWarning('You can use: convert icon.svg -resize 128x128 icon.png');
        // Copy SVG anyway for reference
        await fs.copy(svgIcon, path.join(DIST_DIR, 'icon.svg'));
    } else {
        logWarning('No icon found! Extension will not have an icon.');
    }
}

/**
 * Copy Stockfish files
 */
async function copyStockfishFiles() {
    logStep('Copying Stockfish files...');

    const stockfishFiles = ['stockfish.js', 'stockfish.wasm'];
    const candidateDirs = [
        path.join(PUBLIC_DIR, 'stockfish'),
        PUBLIC_DIR
    ];

    let sourceDir = null;

    for (const dir of candidateDirs) {
        const hasAllFiles = await Promise.all(stockfishFiles.map((file) => fs.pathExists(path.join(dir, file))));
        if (hasAllFiles.every(Boolean)) {
            sourceDir = dir;
            break;
        }
    }

    if (!sourceDir) {
        logWarning('No complete Stockfish JS/WASM pair found in public/ or public/stockfish/.');
        logWarning('This can cause JS/WASM mismatch errors at runtime.');
        return;
    }

    await fs.ensureDir(path.join(DIST_DIR, 'stockfish'));

    for (const file of stockfishFiles) {
        const src = path.join(sourceDir, file);
        await fs.copy(src, path.join(DIST_DIR, file));
        await fs.copy(src, path.join(DIST_DIR, 'stockfish', file));
        logSuccess(`Copied ${file} from ${path.relative(PUBLIC_DIR, sourceDir) || '.'}`);
    }
}

/**
 * Select and copy appropriate manifest
 */
async function copyManifest() {
    logStep(`Copying manifest for ${browserType} (${buildType})...`);

    let manifestFile;

    if (flags.debug) {
        manifestFile = 'manifest.debug.json';
    } else if (browserType === 'firefox') {
        manifestFile = 'manifest.firefox.json';
    } else {
        manifestFile = 'manifest.json';
    }

    const src = path.join(PUBLIC_DIR, manifestFile);
    const dest = path.join(DIST_DIR, 'manifest.json');

    if (await fs.pathExists(src)) {
        await fs.copy(src, dest);
        logSuccess(`Using ${manifestFile}`);
    } else {
        logError(`Manifest ${manifestFile} not found!`);
        throw new Error(`Missing manifest: ${manifestFile}`);
    }
}

/**
 * Bundle source files (simple copy for now)
 */
async function bundleSource() {
    logStep('Bundling source files...');

    // Copy background script
    const backgroundSrc = path.join(SRC_DIR, 'background', 'background.js');
    if (await fs.pathExists(backgroundSrc)) {
        await fs.copy(backgroundSrc, path.join(DIST_DIR, 'background.js'));
        logSuccess('Copied background.js');
    }

    // Build content script from refactored modules
    const builtRefactoredContent = await buildContentScriptBundle();
    if (!builtRefactoredContent) {
        logError('Missing src/content/index.js');
        throw new Error('Cannot build content script from refactored source');
    }

    logSuccess('Built content.js from src/content modules');

    // Copy popup files
    const popupJS = path.join(SRC_DIR, 'popup', 'popup.js');
    const popupHTML = path.join(SRC_DIR, 'popup', 'popup.html');
    const popupCSS = path.join(SRC_DIR, 'popup', 'popup.css');

    if (await fs.pathExists(popupJS)) {
        await fs.copy(popupJS, path.join(DIST_DIR, 'popup.js'));
        logSuccess('Copied popup.js');
    }

    if (await fs.pathExists(popupHTML)) {
        await fs.copy(popupHTML, path.join(DIST_DIR, 'popup.html'));
        logSuccess('Copied popup.html');
    }

    if (await fs.pathExists(popupCSS)) {
        await fs.copy(popupCSS, path.join(DIST_DIR, 'popup.css'));
        logSuccess('Copied popup.css');
    }
}

/**
 * Create package (ZIP or XPI)
 */
async function createPackage() {
    logStep('Creating package...');

    const extension = browserType === 'firefox' ? 'xpi' : 'zip';
    const filename = `chess-assistant-${browserType}-${buildType}.${extension}`;
    const outputPath = path.join(ROOT_DIR, filename);

    const output = fs.createWriteStream(outputPath);
    const archive = archiver('zip', { zlib: { level: 9 } });

    return new Promise((resolve, reject) => {
        output.on('close', () => {
            const sizeMB = (archive.pointer() / 1024 / 1024).toFixed(2);
            logSuccess(`Package created: ${filename} (${sizeMB} MB)`);
            resolve();
        });

        archive.on('error', reject);
        archive.pipe(output);
        archive.directory(DIST_DIR, false);
        archive.finalize();
    });
}

/**
 * Display build summary
 */
function displaySummary() {
    log('\n' + '='.repeat(50));
    log(`${colors.bright}Build Summary${colors.reset}`);
    log('='.repeat(50));
    log(`Browser: ${colors.blue}${browserType}${colors.reset}`);
    log(`Build Type: ${colors.blue}${buildType}${colors.reset}`);
    log(`Output: ${colors.blue}${DIST_DIR}${colors.reset}`);

    if (flags.package) {
        const extension = browserType === 'firefox' ? 'xpi' : 'zip';
        const filename = `chess-assistant-${browserType}-${buildType}.${extension}`;
        log(`Package: ${colors.blue}${filename}${colors.reset}`);
    }

    log('='.repeat(50) + '\n');
}

/**
 * Main build function
 */
async function build() {
    try {
        log('\n' + colors.bright + colors.blue + '╔════════════════════════════════════════╗');
        log('║   Chess Assistant Build Script       ║');
        log('╚════════════════════════════════════════╝' + colors.reset + '\n');

        await clean();
        await copyPublicFiles();
        await copyIcon();
        await copyStockfishFiles();
        await copyManifest();
        await bundleSource();

        if (flags.package) {
            await createPackage();
        }

        displaySummary();

        logSuccess('Build completed successfully!');

        if (!flags.watch) {
            log('\nNext steps:');
            log(`  1. Load extension from ${colors.blue}dist/${colors.reset}`);
            if (browserType === 'firefox') {
                log('  2. Open about:debugging#/runtime/this-firefox');
                log('  3. Click "Load Temporary Add-on"');
                log('  4. Select dist/manifest.json');
            } else {
                log('  2. Open chrome://extensions/');
                log('  3. Enable Developer mode');
                log('  4. Click "Load unpacked"');
                log('  5. Select the dist folder');
            }
        }

    } catch (error) {
        logError('Build failed: ' + error.message);
        console.error(error);
        process.exit(1);
    }
}

/**
 * Watch mode
 */
async function watch() {
    logStep('Starting watch mode...');

    const chokidar = require('chokidar');

    await build();

    const watcher = chokidar.watch([SRC_DIR, PUBLIC_DIR], {
        ignored: /(^|[\/\\])\../,
        persistent: true,
        ignoreInitial: true
    });

    let buildTimeout;

    watcher.on('all', (event, filePath) => {
        log(`\n${colors.yellow}File ${event}: ${path.relative(ROOT_DIR, filePath)}${colors.reset}`);

        // Debounce builds
        clearTimeout(buildTimeout);
        buildTimeout = setTimeout(() => {
            build();
        }, 1000);
    });

    log(`${colors.green}Watching for changes...${colors.reset}\n`);
}

/**
 * Entry point
 */
(async () => {
    if (flags.clean && !flags.watch && !flags.package) {
        await clean();
        return;
    }

    if (flags.watch) {
        await watch();
    } else {
        await build();
    }
})();
